### ISSUE TITLE
New feature request: multiple editor choice at the same time.

### ISSUE THREAD

**Issue by iamwrm** [generalov/open-in-editor-vscode#1]
Hi generalov! I'm really happy that I found such a useful extension. I figured out how to use it run emacsclient and it works just fine. 
I hope you can add the feature that once configured in the user settings, the user can open the current file with different editors from different shortcuts. (eg. Shift+option+E = "open with vim", Shift + opition + R = "open with sublime"

Looking forward to your reply!

**Comment by generalov** [comment]
@iamwrm, thank you. I'm working on it. :)

**Comment by generalov** [comment]
Hi @iamwrm! I've uploaded 0.9.7 release today with ability to open the current file with different editors from different shortcuts. Please look at https://marketplace.visualstudio.com/items?itemName=generalov.open-in-editor-vscode#custom-editors-with-key-bindings for settings example.
