### ISSUE TITLE
Accel key opens vim terminal, but menu command opens gvim.

### ISSUE THREAD

**Issue by dooglio** [generalov/open-in-editor-vscode#4]
Hi there,

Thanks for taking the time to build this extension! I think I found a bug, unless I've got something misconfigured?

I use your extension to open editor buffers in Vim. However, I prefer to use the "gui" version of Viim, `gvim`, instead of the terminal-only command line version `vim`. Here is how I set it up:

In `keybindings.json`:
```
    {
        "key": "ctrl+shift+x",
        "command": "alt-editor.openFile",
        "args": { "name": "vim" },
        "when": "editorTextFocus"
    }
```
In User Settings:
```
    "alt-editor.name": "vim",
    "alt-editor.binary": "/usr/bin/gvim",
    "alt-editor.args": "--servername Code --remote-tab-silent \"+call cursor({line}, {column})\" {filename}",
    "alt-editor.terminal": false
```

Now when I right click and select `Open in External Editor (Ctrl+Shift+X)`, 
![image](https://user-images.githubusercontent.com/643129/35243296-3d1b09f8-ff71-11e7-9cf7-e9807a436fe5.png)

...the file correctly opens in `gvim`:
![image](https://user-images.githubusercontent.com/643129/35243224-f1ebe380-ff70-11e7-8b4e-e54577c7b942.png)

However, when use the accelerator key sequence directly `ctrl+shift+x`, it refuses to send it to my `gvim` instance, and instead opens a terminal and runs the `vim` binary instead:
![image](https://user-images.githubusercontent.com/643129/35243237-fbc4f2de-ff70-11e7-8a16-8332ee7f42f5.png)

No matter what key sequence I try, I cannot get it to work right via the key sequence, but via the menu, it's spot on.

Is there something I'm doing wrong?

**Comment by generalov** [comment]
@dooglio thank you so much for the detailed description. I'll try to check it this weekends.

**Comment by dooglio** [comment]
If there is anything you'd like me to try, or if there is a log file I can access to give you, please let me know.

**Comment by generalov** [comment]
@dooglio I've investigated the issue. It's seems the explicit "args" in the key binding causes that. Could you please remove "args" from the key binding and check if the issue still exists?  
```
  {
        "key": "ctrl+shift+x",
        "command": "alt-editor.openFile",
        "when": "editorTextFocus"
    }
```
Alternatively it's needed to repeat all settings in the "args":
```
  {
        "key": "ctrl+shift+x",
        "command": "alt-editor.openFile",
        "args": { 
          "name": "vim",
          "binary": "/usr/bin/gvim",
          "args": "--servername Code --remote-tab-silent \"+call cursor({line}, {column})\" {filename}",
          "terminal": false
        },
        "when": "editorTextFocus"
    }
```

**Comment by dooglio** [comment]
When I remove the `args` entry from the key bindings, it works!
